language: cpp
sudo: required
dist: trusty
branches:
  only:
    - master
os:
  - linux

env:
  - CONFIG=Release MIDIEDITOR_RELEASE_VERSION_ID=2 MIDIEDITOR_RELEASE_VERSION_STRING=3.1.0 MIDIEDITOR_PACKAGE_VERSION=1 MIDIEDITOR_BINARY=MidiEditor MXE=/usr/lib/mxe/ PATH=$MXE/usr/bin:$PATH INSTALLJAMMER=installjammer/installjammer MIDIEDITOR_BINARY_WINDOWS=windows32_build/.build/bin/MidiEditor.exe

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
    - sudo apt-get install qt5-default qttools5-dev-tools
    - QT_VERSION_MM=59
    - QT_VERSION_FULL=591-trusty
    - sudo apt-get install libsfml-dev
    - sudo apt-get install libasound2-dev
    - sudo apt-get install curl
    - sudo apt-get install fakeroot
    # For mxe.cc (see http://mxe.cc/#requirements)
    - echo 'deb http://pkg.mxe.cc/repos/apt/debian wheezy main' | sudo tee -a /etc/apt/sources.list.d/mxeapt.list
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
    - sudo apt-get update
    - sudo apt-get install mxe-i686-w64-mingw32.static-qtbase
    
before_script:

script:
   - sh building/build-windows.sh
   - sh building/build-linux.sh
   - sh packaging/unix/build_deb.sh
   - git clone https://github.com/damoncourtney/installjammer.git installjammer
   - cd installjammer
   - git tag -l
   - git checkout tags/v1.2.14
   - ls -la
   - file installjammer
   - cd ../
   - sh packaging/windows/create_windows_setup.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: local
  master-dir: deb
